### ISSUE TITLE
Cannot find module 'svelte-virtual@next' in SvelteKit

### ISSUE THREAD

**Issue by Enable-Lukas** [ghostebony/svelte-virtual#54]
First of all, it's a cool library conceptually, but I'm having trouble getting it to work. I installed it with npm and then tried to run the first example with the list. However, when I follow the tutorial, there are issues with SSR, and it can't find the path. Could it be that the library is not compatible with SvelteKit?

Svelte versions:
```
$ npm ls|grep -i svelte
├── @neoconfetti/svelte@2.2.1
├── @sveltejs/adapter-auto@3.2.4
├── @sveltejs/kit@2.5.24
├── @sveltejs/vite-plugin-svelte@3.1.1
├── @unovis/svelte@1.4.3-beta.0
├── eslint-plugin-svelte@2.43.0
├── lucide-svelte@0.438.0
├── prettier-plugin-svelte@3.2.6
├── svelte-check@3.8.5
├── svelte-headless-table@0.18.2
├── svelte-legos@0.2.5
├── svelte-virtual@1.0.0-next.17
├── svelte@4.2.19
├── vaul-svelte@0.3.2
```

`Cannot find module 'svelte-virtual@next' imported from 'C:/Users/l-brostering/VS Code/Frontend/src/routes/VirtuelleTabelle.svelte'`

```
14:07:56 [vite] Pre-transform error: Failed to load url svelte-virtual@next (resolved id: svelte-virtual@next) in C:/Users/l-brostering/VS Code/Frontend/src/routes/VirtuelleTabelle.svelte. Does the file exist?
14:07:58 [vite] Error when evaluating SSR module /src/routes/VirtuelleTabelle.svelte: failed to import "svelte-virtual@next"
|- Error: Cannot find module 'svelte-virtual@next' imported from 'C:/Users/l-brostering/VS Code/Frontend/src/routes/VirtuelleTabelle.svelte'
    at nodeImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (eval at instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52906:24), <anonymous>:4:37)
    at async instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5)

14:07:58 [vite] Error when evaluating SSR module /src/routes/dashboard/+page.svelte: failed to import "svelte-virtual@next"
|- Error: Cannot find module 'svelte-virtual@next' imported from 'C:/Users/l-brostering/VS Code/Frontend/src/routes/VirtuelleTabelle.svelte'
    at nodeImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (eval at instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52906:24), <anonymous>:4:37)
    at async instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5)

Error: Cannot find module 'svelte-virtual@next' imported from 'C:/Users/l-brostering/VS Code/Frontend/src/routes/VirtuelleTabelle.svelte'
    at nodeImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (eval at instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52906:24), <anonymous>:4:37)
    at async instantiateModule (file:///C:/Users/l-brostering/VS%20Code/Frontend/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Let me know if you'd like further help with troubleshooting this issue!

**Comment by Enable-Lukas** [comment]
Fix: Change 	
import { List } from 'svelte-virtual@next';
to
import { List } from 'svelte-virtual';
